### ISSUE TITLE
defaultRerollPaymentItem does not change

### ISSUE THREAD

**Issue by onycius** [fzzyhmstrs/gearifiers#8]
Changing the defaultRerollPaymentItem to a different item does not apply in-game. The config saves but the REI recipe remains as a default diamond. I'm not sure if I'm doing it correctly or if this is a bug, so it'd be great if you'd take a look at this!

Also, it would be nice if the diamond overlay in the reroll item slot of the reroll altar is removed. This allows for consistency with any reroll item--not just diamonds.

Thanks so much in advance!

**Comment by fzzyhmstrs** [comment]
this should be fixed as of 0.4.0

**Comment by GenericDwarf** [comment]
Can confirm this issue isn't yet fixed. As of 0.4.0, reroll tables still ignore all of the config file tweaks you make, including exp cost and reroll item changes.

**Comment by fzzyhmstrs** [comment]
@GenericDwarf that sounds like you aren't updating the cobfig correctly, because I'm in an active SMP where changes to the config are definitely being applied

**Comment by GenericDwarf** [comment]
[Here](https://pastebin.com/R4UKaZFB) is how both my client and server config is set up. Despise this, the reroll table still takes 5 levels, still adds 3 levels on top of each reroll, and still requests for a diamond for a sucessful reroll.

**Comment by fzzyhmstrs** [comment]
That is a legitimate issue, but not related to why the problem in this issue ticket was happening. Delete this bit and the config will start working again, that's not supposed to be there:
![image](https://github.com/fzzyhmstrs/gearifiers/assets/72876796/e3500949-fb8b-4f73-b17b-f221b0a3e742)

**Comment by GenericDwarf** [comment]
Deleting it made it so nothing is acceptable for a reroll anymore. Tried changing from Numismatic Overhaul gold coin to vanilla lapis, and even to the default diamond cost. Nothing, items simply refuse to be rerolled.
